### ISSUE TITLE
Feature request: Syntax for alternatives 

### ISSUE THREAD

**Issue by SlimeDog** [SrBedrock/PluginControl#3]
When I am testing alternative resources (for example, DecentHolograms and HolographicDisplays), I have to switch between different versions of the PluginControl configuration, or disable PluginControl temporarily.

#### Describe the solution you'd like

A syntax to permit alternatives. For example (verified legal with [YAML lint](http://www.yamllint.com))
```
enabled: true
plugins:
  - Citizens
  - 
    signs: 
      - CommandSigns
      - ServerSigns
  - ConsoleSpamFix
  - 
    holograms: 
      - DecentHolograms
      - HolographicDisplays
  - DeluxeMenus
```
I prefer legal YAML, but any syntax that permits alternatives would be great.

In this conception, at least one of the alternatives must be enabled. Perhaps a WARN message should be logged if more than one is enabled, but that should be allowed.

#### Describe alternatives you've considered

Switching configurations, as I do now.
